[package]
name = "kacl-parser"
version = "0.1.0"
authors = ["Mr-Andersen <andrassy_anderson@protonmail.com>"]
edition = "2018"

[dependencies]
comrak = "0.10"
itertools = "0.10"
nom = "6.1"
versions = "2.1"
